Vagrant.configure("2") do |config|
  config.vm.box = "ramsey/macos-catalina"
  config.vm.box_version = "1.0.0"
  config.vm.hostname = "mac-vm"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "C:/Users/zubko/vagrant_vms/provisioning/mac_setup.sh"
end
